### ISSUE TITLE
Unify StringSegment/TextSpan

### ISSUE THREAD

**Issue by candoumbe** [datalust/superpower#113] opened 2020-05-19 09:41 UTC
Recently, .NET landed the new `StringSegment` structure and I think this library could benefit of it.
It seems that the `TextSpan` class serves the same purpose and this project could greatly benefit
Am I right ?
I started working on a small project called [DataFilters](https://dev.azure.com/candoumbe/DataFilters) that extensively uses this library to build a kinda generic search syntax and I must say I really enjoyed working with this library so far.

**Comment by chrisspre** [comment] 2020-07-10 21:37
StringSegment seems to be not very different from ReadOnlySpan<char>/ReadOnlyMemory<char> 
Would moving to ReadOnlySpan<char> (or a wrapper around ReadOnlySpan<char> that captures line and column numbers) be another option ?

**Comment by AndrewSav** [comment] 2020-08-14 21:11
@candoumbe @chrisspre what problem are you trying to solved? To me it seems that `TextSpan` is working well for what it was designed. Also it is not possible to change `StringSegment`/`ReadOnlySpan` for our purposes, and they do not have `Position` so in any case a new class will have to be created, similar to `TextSpan`. Which is already there and working well.

Could you please expand a bit more on benefits of your proposal, balanced vs additional work to implement it?

**Comment by candoumbe** [comment] 2020-08-14 21:19
> @candoumbe @chrisspre what problem are you trying to solve? To me it seems that `TextSpan` is working well for what it was designed. Also it is not possible to change `StringSegment`/`ReadOnlySpan` for our purposes, and they do not have `Position` so in any case a new class will have to be created, similar to `TextSpan`. Which is already there and working well.
> 
> Could you please expand a bit more on benefits of your proposal, balanced vs additional work to implement it?

Hi !
It was only a question and not a request to modify the existing code. I did not do a thorough analysis of the changes this would require and  am more than happy with the way this library is now. In fact, I successfully used it to create a parser of my own

**Closed** 2020-12-02 03:21 UTC
